### PR TITLE
Adding phantomjs support

### PR DESCRIPTION
**Pull request by admwx7**
Was able to add in the binary and run my tests against phantomjs without any issues.

### CODE REVIEW

**Comment by admwx7** [comment]
I signed it!

**Comment by stramel** [comment]
Really hoping we can get this merged, is there a status update on this?

**Comment by ankon** [comment]
Any help needed to get this forward?

**Comment by justinfagnani** [comment]
There've been a lot of changes, so this PR needs to be rebased.

**Comment by admwx7** [comment]
Moving this over to #34 since the inline editor for github didn't create a branch I could rebase against...

**Pull request closed without merging**
