### PR TITLE
Temporary blacklist of firefox >46

### PR DESCRIPTION
**Pull request by rictic**

### CODE REVIEW

**Comment by robdodson** [comment]
LGTM :P

**Comment by azakus** [comment]
LGTM2

**Comment by robdodson** [comment]
awwww yisssss.

so now do i need to wait for a new release of wct-local?

**Comment by rictic** [comment]
Yes, I'm working on it now

**Comment by rictic** [comment]
Published as `v2.0.10`

**Comment by robdodson** [comment]
@rictic because I'm using CLI to test do i need to reinstall polymer-cli to get this change?

**Comment by rictic** [comment]
That sounds right? I'm not 100% sure.

**Pull request merged**
